services:
  - type: web
    name: business-accounting-app
    env: docker
    build:
      dockerfile: Dockerfile
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
      - key: PORT
        value: "10000"
      - key: NODE_ENV
        value: "production"
      - key: VITE_API_BASE_URL
        value: "https://business-accounting-app.onrender.com"
    # Health check configuration
    healthCheckPath: /api/health
    # Auto-deploy from GitHub
    autoDeploy: true
    # Resource allocation (adjust based on your needs)
    plan: free
    numInstances: 1
    # Build command (handled by Dockerfile)
    buildCommand: ""
    # Start command (handled by Dockerfile)
